// src/components/Area.jsx
import React from 'react';
import SelectField from './SelectField'; // Assuming SelectField.jsx is in the same directory

const Area = () => {
    const areaOptions = [
        'Aberdeen',
        'Awarding Bodies',
        'Bath',
        'Belfast',
        'Birmingham',
        'Blackburn',
        'Blackpool',
        'Bolton',
        'Bournemouth',
        'Bradford',
        'Brighton',
        'Bristol',
        'Bromley',
        'Canterbury',
        'Carlisle',
        'Chelmsford',
        'Chester',
        'Cleveland',
        'Colchester',
        'Comhairle nan Eilean Siar',
        'Coventry',
        'Crewe',
        'Croydon',
        'Darlington',
        'Dartford',
        'Derby',
        'Dudley',
        'Dumfries',
        'Dundee',
        'Durham',
        'Edinburgh',
        'Enfield',
        'Exeter',
        'Falkirk',
        'Galashiels',
        'Glasgow',
        'Gloucester',
        'Guernsey',
        'Guilford',
        'Halifax',
        'Harrogate',
        'Harrow',
        'Hemel',
        'Hereford',
        'Huddersfield',
        'Hull',
        'Ilford',
        'Inverness',
        'Ipswich',
        'Isle of Man',
        'Jersey',
        'Kilmarnock',
        'Kingston',
        'Kirkaldy',
        'Kirkwall',
        'Lancaster',
        'Leeds',
        'Leicester',
        'Liverpool',
        'Llandrindod',
        'London',
        'Luton',
        'Manchester',
        'Medway',
        'Milton Keynes',
        'Motherwell',
        'Newcastle',
        'Paisley',
        'Perth',
        'Peterborough',
        'Plymouth',
        'Portsmouth',
        'Preston',
        'Reading',
        'Redhill',
        'Romford',
        'Salisbury',
        'Sheffield',
        'Shetland',
        'Shrewsbury',
        'Slough',
        'Southampton',
        'Southall',
        'St. Albans',
        'Stevenage',
        'Stockport',
        'Stoke on Trent',
        'Sunderland',
        'Sutton',
        'Swansea',
        'Swindon',
        'Taunton',
        'Telford',
        'Tonbridge',
        'Torquay',
        'Truro',
        'Twickenham',
        'Wakefield',
        'Walsall',
        'Warrington',
        'Watford',
        'Wigan',
        'Wolverhampton',
        'Worcester',
        'York',
    ].sort();

    return (
        <SelectField label="Area" name="Area" options={areaOptions} />
    );
};

export default Area;